/* auto-generated by NAPI-RS */
/* eslint-disable */
export interface Comment {
  start: number
  end: number
  text: string
}

export interface ModuleImports {
  name: string
}

function reactServerAction(filePath: string, actionExportPrefix: string, isServerLayer: boolean): Promise<string>

export const enum RSCError {
  CannotUseBothClientAndServer = 0,
  ServerActionMustBeAsync = 1
}

function shit(): void

function validate(filePath: string): Promise<ValidateResult>

export interface ValidateResult {
  isClientEntry: boolean
  isServerAction: boolean
  error?: RSCError
  imports: Array<ModuleImports>
}

