/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export function validate(filePath: string): Promise<ReactServerComponent>
export const enum FileType {
  ServerComponent = 0,
  ServerAction = 1,
  Client = 2,
  Isomorphic = 3,
}
export interface ReactServerComponent {
  fileType: FileType
  error?: string
}
