/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface ValidateResult {
  isClientEntry: boolean
  isServerAction: boolean
  error?: RSCError
  imports: Array<ModuleImports>
}
export const enum RSCError {
  CannotUseBothClientAndServer = 0,
  ServerActionMustBeAsync = 1
}
export interface ModuleImports {
  name: string
}
export function validate(filePath: string): Promise<ValidateResult>
